name: after_spor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_webrtc: ^0.12.11  # Stelle sicher, dass dies die neueste Version ist
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.4.0



dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/galatasaray.png
      - assets/fenerbahce.png
      - assets/login.png
